My_Parking_Charge/urls.py
from django.urls import path
from . import views, Ajax_check, data_interface
from django.contrib.auth import views as auth_views

app_name = "My_Parking_Charge"
urlpatterns = [
    path('fo/', views.forloopd),  # 登陆url
    path('login/', views.mylogin, name="mylogin"),  # 登陆url
    path('register/', views.register, name="myregister"),  # 注册url

    path('index/', views.index, name="myindex"),  # 后台url
    # path('base/', views.base, name="base"),  # 测试url
    path('logout/', auth_views.LogoutView.as_view(template_name="logout.html"), name='user_logout'),  # 退出
    # template_name=''
    path('usual/', views.usual, name="myusual"),  # 后台常规用户url
    path('VIP/', views.VIP, name="myVIP"),  # 后台VIP用户url

    # 查看iframe页面
    path('vip_detail_iframe/', views.vip_detail_iframe, name="vip_detail_iframe"),
    # 编辑iframe页面
    path('vip_edit_iframe/', views.vip_edit_iframe, name="vip_edit_iframe"),

    # 二维码的iframe
    path('QRcode_iframe/', views.QRcode_iframe, name="QRcode_iframe"),


    path('usual_iframe/', views.usual_iframe, name="usual_iframe"),

    # VIP收费
    path('free/', views.free, name="free"),

    # Ajax 验证
    path('login_ajax/', Ajax_check.admin_login, name="admin_login"),  # ajax验证登陆url
    path('VIPdelete/', Ajax_check.VIPdelete, name="VIPdelete"),  # ajax验证登陆url
    path('VIPregister/', Ajax_check.VIPregister, name="VIPregister"),  # 会员注册ajax url
    path('VIPedit/', Ajax_check.VIPedit, name="VIPedit"),  # 会员编辑ajax url
    path('usual_add/', Ajax_check.usual_add, name="usual_add"),  # 会员编辑ajax url
    path('usualdelete/', Ajax_check.usualdelete, name="usualdelete"),  # 常规记录 ajax url

    path('usual_update/', Ajax_check.usual_update, name="usual_update"),  # 常规更新 ajax url
path('free_update/', Ajax_check.free_update, name="free_update"),  # 收费更新 ajax url



    # 数据接口

    # 常规用户数据接口
    path('usual_data_interface/', data_interface.usual_data_interface, name='usual_data_interface'),

    # 会员用户数据接口
    path('VIP__data_interface/', data_interface.VIP__data_interface, name='VIP__data_interface'),

    # 用户收费数据接口
    path('free_data_interface/', data_interface.free_data_interface, name='free_data_interface'),

]

Parking_Charge/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('My_Parking_Charge.urls', namespace='My_Parking_Charge')),
]

My_Parking_Charge/models.py
from django.db import models


# Create your models here.


class VIPuserInfo(models.Model):  # 会员用户信息注册表
    user_nanme = models.CharField(max_length=30, verbose_name="用户昵称", null=False, blank=False)
    user_ID = models.CharField(max_length=50, verbose_name="用户车牌号", unique=True, null=False, blank=False)
    uer_rank = models.IntegerField(default=1, null=False, blank=False, verbose_name="会员等级")
    user_phone = models.CharField(max_length=20, verbose_name="用户手机号", null=False, blank=False)
    user_birth = models.DateField(verbose_name="用户出生年月日", null=False, blank=False)
    user_sex = models.CharField(max_length=6, verbose_name="用户性别", null=False, blank=False)
    user_grade = models.CharField(max_length=10, verbose_name="用户年龄", null=False, blank=False)

    class meta:
        verbose_name = "会员用户注册"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user_ID


class User_Info(models.Model):  # 往来用户记录信息表
    GENDER_CHOICE = (("0","常规用户"), ("1", "会员"))
    user_ID = models.CharField(max_length=50, verbose_name="用户车牌号", null=False, blank=False)
    user_choise = models.CharField(choices=GENDER_CHOICE,verbose_name="是否会员",max_length=10)
    user_starttime = models.DateTimeField(verbose_name="停车时间", blank=True, null=True, auto_now_add=False)
    user_endtime = models.DateTimeField(verbose_name="结束停车时间", blank=True, null=True,auto_now_add=False )



    class meta:
        verbose_name = "往来用户记录信息表"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.user_ID







class user_charge(models.Model):  #往来用户收费表
    user_id = models.ForeignKey("User_Info",on_delete=models.CASCADE,verbose_name="用户外键",related_name="us")
    user_free = models.CharField(max_length=60,verbose_name="产生费用",blank=True,null=True)
    end_free_time = models.DateTimeField(verbose_name="清算费用时间",blank=True,null=True)


    class meta:
        verbose_name = "往来用户收费表"
        verbose_name_plural = verbose_name


    def __str__(self):
        return self.user_id

Test/models.py
from django.db import models

# Create your models here.

Tests/models.py
from django.db import models

# Create your models here.

My_Parking_Charge/forms.py
from  django import  forms

class LoginForm(forms.Form):
    username = forms.CharField()
    psd = forms.CharField(widget=forms.PasswordInput)

My_Parking_Charge/views.py
from django.shortcuts import render, HttpResponse
from django.views.decorators.http import require_POST
from django.views.decorators.csrf import csrf_exempt
from  . import models
import  datetime
import django
from django.contrib.auth.hashers import make_password, check_password
from django.contrib.auth.decorators import login_required
from . import  forloop1
# Create your views here.


# //管理员登录

@csrf_exempt
def mylogin(request):
    if request.method == "GET":
        return render(request, "Login.html")
    elif request.method == "POST":
        return HttpResponse("1")


# 会员注册
@csrf_exempt
@login_required()
def register(request):
    if request.method == "GET":
        return render(request, "register.html")
    elif request.method == "POST":
        user_ID = request.POST.get("user_number")
        user_name = request.POST.get("user_name")
        user_phone = request.POST.get("user_phone")
        user_birth =request.POST.get("user_birth")
        user_sex = request.POST.get("user_sex")
        birth_day = int(user_birth[0:4])
        now_year = int(datetime.datetime.now().year)
        grade = str(now_year - birth_day)
        print(user_ID, user_name, user_phone, user_birth, user_sex)
        if user_sex == None:
            return  HttpResponse("0")
        else:
            models.VIPuserInfo.objects.create(user_ID=user_ID,user_nanme=user_name,user_phone=user_phone
                                          ,user_birth=user_birth,user_sex=user_sex,user_grade=grade)

        return HttpResponse("1")








# 后台主页
@csrf_exempt
@login_required()
def index(request):
    print(django.get_version())
    return render(request, "index.html")


@csrf_exempt
@login_required()
def usual(request):
    return render(request, "usual.html",{'user_type':"usual"})


@csrf_exempt
@login_required()
def VIP(request):
    user_type = "VIP"
    return render(request, "usual.html",{'user_type':user_type})



# 查看的 iframe
@csrf_exempt
def vip_detail_iframe(request):
    return render(request,"iframe.html",context= { 'vip_type':"detail"})


# 编辑 的 iframe
def vip_edit_iframe(request):
    return render(request,"iframe.html",context= {'vip_type':"edit"})

#二维码的iframe
def QRcode_iframe(request):
    return render(request,"iframe.html",context= {'free':"free"})

def usual_iframe(request):
    return render(request,"iframe.html",context={"usual":"usual"})


@login_required()
def free(request):
    return render(request,"usual.html",context={"free":"free"})





def forloopd(request):
    forloop1.fo()
    return  HttpResponse("....................")

Test/views.py
from django.shortcuts import render

# Create your views here.

Tests/views.py
from django.shortcuts import render

# Create your views here.

templates/Login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    {#    <meta http-equiv="Page-Enter" content="revealTrans(duration=6, transition=5)">#}
    <title>智能收费系统后台管理员登录</title>
    <link rel="stylesheet" href={% static "css/style.css" %}>
    <link rel="stylesheet" href={% static "css/bootstrap.css" %}>
    <link rel="stylesheet" href={% static "layui/css/layui.css" %}>
    <script src={% static "js/jquery-2.1.1.js" %} type="text/javascript" charset="utf-8"></script>
</head>
<body>
<div id="particles-js">
    <div class="login" style="display: block;">
        <div class="form-group">
            <h1 style="color: ghostwhite; margin-left: 60px;">智能停车收费系统</h1>
        </div>
        <br>
        <form class="form-horizontal">
            <div class="form-group">
                <label style="text-align: center; color: ghostwhite; font-size: 16px;"
                       class="col-sm-3 control-label "><span class="glyphicon glyphicon-user"></span>&nbsp;用户名:</label>
                <div class="col-sm-8">
                    <input style="background-color:transparent;border:1;color: white" class=" input-lg form-control"
                           type="text"
                           name="username" id="username" value="" placeholder="请输入您的用户名">
                </div>
            </div>
            <div class="form-group">
                <label style="text-align: center; color: ghostwhite;  font-size: 16px;" class="col-sm-3 control-label "><span
                        class="glyphicon glyphicon-lock">
							</span>&nbsp;密 &nbsp;&nbsp;码:</label>
                <div class="col-sm-8">
                    <input style="background-color:transparent;border:1;color: white" class="input-lg form-control"
                           type="password"
                           name="password" id="password" value="" placeholder="请输入您的密码">
                </div>
            </div>
            <br>
            <div class="form-group ">
                <div class="col-sm-3">

                </div>
                <div class="col-sm-8">
                    <a class="form-control input-lg btn btn-primary btn-lg" id="xadmin_login">
                        <b style="color: lightcyan;">登录</b></a>
                </div>
            </div>
        </form>
    </div>
    <div class="sk-rotating-plane"></div>
    <canvas class="particles-js-canvas-el" width="1147" height="952" style="width: 100%; height: 100%;"></canvas>
</div>
<script src= {% static "js/particles.min.js" %}></script>
<script src= {% static "js/app.js" %}></script>
<script src= {% static "layui/layui.all.js" %}></script>
<script type="text/javascript">
    function hasClass(elem, cls) {
        cls = cls || '';
        if (cls.replace(/\s/g, '').length == 0) return false; //当cls没有参数时，返回false
        return new RegExp(' ' + cls + ' ').test(' ' + elem.className + ' ');
    }

    function addClass(ele, cls) {
        if (!hasClass(ele, cls)) {
            ele.className = ele.className == '' ? cls : ele.className + ' ' + cls;
        }
    }

    function removeClass(ele, cls) {
        if (hasClass(ele, cls)) {
            var newClass = ' ' + ele.className.replace(/[\t\r\n]/g, '') + ' ';
            while (newClass.indexOf(' ' + cls + ' ') >= 0) {
                newClass = newClass.replace(' ' + cls + ' ', ' ');
            }
            ele.className = newClass.replace(/^\s+|\s+$/g, '');
        }
    }

    function login() {
        var username = $("#username").val().replace(/(^\s*)|(\s*$)/g, "");
        var password = $("#password").val().replace(/^\s+|\s+$/g, '');
        console.log(username, password);
        if (username == '' || password == '') {
            layer.msg("不可为空，请输入正确格式", {icon: 5})
        } else {


            //ajax登录
            $.ajax({
                url: " {% url "My_Parking_Charge:admin_login" %}",
                type: "POST",
                dataType: 'json',
                data: {"username": username, "psd": password},
                success: function (e) {
                    if (e == "1") {

                        {#                        {% if next %}#}
                        {#                       setTimeout(function () {#}
                        {#                            location.href ='#}
                        {#                            {% url "My_Parking_Charge:admin_login" %}?next={{next}}'#}
                        {#                        }, 1000);//延时登陆#}
                        {#                                 console.log("dadwadawdaw")#}
                        {#                        {% else %}#}
                        var index = layer.load(0, {shade: false}); //0代表加载的风格，支持0-2


                        setTimeout(function () {
                            layer.close(index)
                            layer.msg("登录成功", {icon: 1})
                        }, 1500)
                        setTimeout(function () {
                            location.href =
                            {% url "My_Parking_Charge:myindex" %}
                        }, 2000);//延时登陆
                        {#                        {% endif %}#}

                    } else {
                        layer.msg("登录失败", {icon: 2});

                    }
                },
            })
        }
    }

    console.log(window.location.href)
    /*
    * 鼠标单击 和键盘 enter 都可以
    *
    * */
    $("#xadmin_login").click(function () {
        login()

    })
    $(document).keydown(function (event) {
        if (event.which == 13) {
            login()
        } else {
            console.log("Key: " + event.which)
        }
    })


</script>
</body>
</html>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <title>{% block title %}智能收费系统{% endblock %}</title>
    <link rel="stylesheet" href={% static "layui/css/layui.css" %}>
    <link rel="stylesheet" href={% static "css/layui-theme-custom.css" %}>
    <script src={% static "js/jquery-2.1.1.js" %}></script>

</head>
<body class="layui-layout-body">
<div class="layui-layout layui-layout-admin">
    <div class="layui-header layui-bg-cyan">
        <div><a class="layui-logo" href="{% url "My_Parking_Charge:myindex" %}"><b style="font-size: 24px;">智能收费系统</b></a></div>
        <!-- 头部区域（可配合layui已有的水平导航） -->
        </ul>
        <ul class="layui-nav layui-layout-right">
            {% if user.is_authenticated %}
                <li class="layui-nav-item">
                    <a href="javascript:;">

                        <img src="/static/img/5318ab688977d41445fabb118c0d039e.jpg"
                             class="layui-nav-img">
                        {{ user.username }}
                    </a>
                    <dl class="layui-nav-child">
                        <dd><a href="javascript:void (0);">基本资料</a></dd>
                        <dd><a href="javascript:void (0);">安全设置</a></dd>
                    </dl>

                </li>

                <li class="layui-nav-item"><a href="{% url "My_Parking_Charge:user_logout" %}">注销</a></li>
            {% else %}
                <li class="layui-nav-item">
                    <a href="{% url "My_Parking_Charge:mylogin" %}">
                        LOGIN
                    </a>
                </li>
            {% endif %}
        </ul>
    </div>

    <div class="layui-side layui-bg-cyan">
        <div class="layui-side-scroll">
            <!-- 左侧导航区域（可配合layui已有的垂直导航） -->
            <ul class="layui-nav layui-nav-tree ">
                <li class="layui-nav-item layui-nav-itemed">
                    <a class="" href="javascript:;">用户管理</a>
                    <dl class="layui-nav-child ">
                        <dd><a href="{% url "My_Parking_Charge:myusual" %}">用户记录信息</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item">
                    <a href="javascript:;">会员管理</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url "My_Parking_Charge:myVIP" %}">会员基本信息</a></dd>
                    </dl>
                </li>
                <li class="layui-nav-item">
                    <a href="javascript:;">收费管理</a>
                    <dl class="layui-nav-child">
                        <dd><a href="{% url "My_Parking_Charge:free" %}">收费记录</a></dd>

                    </dl>
                </li>
            </ul>
        </div>
    </div>

    <style>
        html {
            height: 100%;
            width: 100%;
            background-size: 100% 100%;

            background-image: url("https://wallpaperm.cmcm.com/2d64f9b1d09b9c519b301d4d721adc0c.jpg");
            background-repeat: no-repeat;
        }

    </style>


    <div class="layui-body">
        <!-- 内容主体区域 -->
        <div style="padding: 15px;" id="bg">
            {% block content %}
                <b style="font-size: 32px;text-align: center">欢迎登录智能收费系统</b>
                {% block script %}
                    <script src={% static "layui/layui.js" %}></script>{% endblock %}
            {% endblock %}
        </div>
    </div>

    <div class="layui-footer" style="background-color: transparent">
        <!-- 底部固定区域 -->
        <p><i style="font-size: 18px">@</i> <b style="font-size: 16px;font-family: 华文楷体">余子怡 朱华超 张思伟 刘佳伟 窦建国 汝双双 王能宇</b></p>
    </div>

</div>

<script>
    //JavaScript代码区域
    layui.use('element', function () {
        var element = layui.element;
    });

    var integrityurl = window.location.href;
    console.log("当前URL为:", integrityurl);


    //页面跳转共用导航样式不变
    $(document).ready(function () {
        $(".layui-side .layui-nav-item dl dd a").each(function () {
            $this = $(this);
            if ($this[0].href == String(window.location)) {
                $this.parent().addClass("layui-this");
                $this.parent().parent().parent().addClass('layui-nav-itemed');
                $this.parent().parent().parent().prevAll().removeClass('layui-nav-itemed');
                $this.parent().parent().parent().nextAll().removeClass('layui-nav-itemed');

            }
        });
    });


</script>
</body>
</html>

templates/logout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>注销</title>
    <link rel="stylesheet" href={% static "layui/css/layui.css" %}>
    <link rel="stylesheet" href={% static "css/layui-theme-custom.css" %}>
</head>
<style>
    html {
        height: 100%;
        width: 100%;
        background-size: 100% 100%;
        background-image: url("/static/img/5318ab688977d41445fabb118c0d039e.jpg");
        background-repeat: no-repeat;

    }

</style>
<body>
<div class="layui-container">

    <div class="layui-row layui-col-space10" style="margin: 100px auto">
        <div class="layui-col-md6"><p style="text-align: left"><b style="font-size: 26px">感谢您今天在本站花费了一些宝贵时间。</b></p>
            <br>
            <p style="text-align: left"><b style="font-size: 26px">酒盈杯，书满架，名利不将心挂。</b></p>
            <br>
                <p style="text-align: left"><b style="font-size: 26px">清溪深不测，隐处唯孤云。</b></p>
            <br><br>
            <p style="text-align: right"><b><a style="color: #0000FF;font-size: 20px" href="{% url 'My_Parking_Charge:mylogin' %}">重新登录</a></b></p>
        </div>
        <div class="layui-col-md1"></div>
        <div class="layui-col-md5">
            <img width="100%" class="layui-layer-imguider"
                 src="http://img.netbian.com/file/2020/0904/dbb00a5646309df5fad6efda1079e756.jpg" alt="">
        </div>
    </div>
</div>
</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <title>VIP注册</title>
        <link rel="stylesheet" href={% static "css/style.css" %}>
        {#    <link rel="stylesheet" href={% static "css/bootstrap.css" %}>#}
        <link rel="stylesheet" href={% static "layui/css/layui.css" %}>
         <link rel="stylesheet" href={% static "css/layui-theme-custom.css" %}>
        <script src={% static "js/jquery-2.1.1.js" %} type="text/javascript" charset="utf-8"></script>
    </head>
</head>
<body>
<ul class="layui-nav">
    <li class="layui-nav-item"><a style="font-family: 华文楷体;font-size: 20px " href="{% url "My_Parking_Charge:myindex" %}">首页</a></li>
    <li class=" layui-nav-item layui-icon layui-icon-right"></li>
    <li class="layui-nav-item layui-this"><a style="font-family: 华文楷体;font-size: 20px " href="">VIP注册</a></li>
</ul>

<div class="layui-container">
    <div class="layui-row layui-col-space10">
        <div class="layui-col-md4"></div>
        <div class="layui-col-md4"></div>
        <div class="layui-col-md4"></div>
    </div>

    <div class="layui-row layui-col-space10">
        <div class="layui-col-md4"></div>
        <div class="layui-col-md4">
            <form method="post" action="{% url "My_Parking_Charge:myregister" %}" class="layui-form layui-form-pane "
                  style="margin-top: 100px; font-size: 14px;font-family:方正粗黑宋简体">

                <div class="layui-form-item" pane>
                    <label class="layui-form-label">车牌号</label>
                    <div class="layui-input-block">
                        <input id="user_number" type="text" name="user_number" required lay-verify="required"
                               placeholder="请输入车牌号"
                               autocomplete="off" class="layui-input">
                    </div>

                </div>
                <div class="layui-form-item" pane>
                    <label class="layui-form-label">用户昵称</label>
                    <div class="layui-input-block">
                        <input id="user_number1" type="text" name="user_name" required lay-verify="required"
                               placeholder="请输入用户昵称"
                               autocomplete="off" class=" layui-input">
                    </div>
                </div>
                <div class="layui-form-item" pane>
                    <label class="layui-form-label">用户手机号</label>
                    <div class="layui-input-block">
                        <input id="user_number3" type="text" name="user_phone" required lay-verify="required"
                               placeholder="请输入用户手机号"
                               autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item" pane>
                    <label class="layui-form-label">出生年月日</label>
                    <div class="layui-input-block">
                        <input  id="user_number4" type="text" name="user_birth" required lay-verify="required"
                               placeholder="请输入出生年月日"
                               autocomplete="off" class="layui-input">
                    </div>
                </div>
                <div class="layui-form-item">
                    <label class="layui-form-label">性别</label>
                    <div class="layui-input-block">
                        &nbsp; &nbsp;
                        <input type="radio"  name="sex" value="男" title="男">
                        &nbsp; &nbsp;
                        <input type="radio" name="sex" value="女" title="女">
                    </div>
                </div>
                <br><br>
                <div class="layui-form-item">
                    <div class="layui-input-block">
                        <button class="layui-btn" lay-submit lay-filter="formDemo">立即提交</button>
                        <button type="reset" class="layui-btn layui-btn-primary">重置</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="layui-col-md4">
            <div class="layui-row" style="margin-top: 100px">
                <span id="user_span" class="layui-icon "
                      style="color: rgb(0, 255, 64);font-size: 36px;"></span>
                <br><br>
                <span id="user_span1" class=" layui-icon "
                      style="color: rgb(0, 255, 64);font-size: 36px;"></span>
                <br><br>
                <span id="user_span2" class="layui-icon "
                      style="color: rgb(0, 255, 64);font-size: 36px;"></span>
                <br><br>
                <span id="user_span3" class=" layui-icon "
                      style="color: rgb(0, 255, 64);font-size: 36px;"></span>
                <br><br>
                <span id="user_span4" class=" layui-icon   "
                      style="color: rgb(0, 255, 64);font-size: 36px;"></span>
            </div>
        </div>

    </div>


</div>
<script src= {% static "layui/layui.all.js" %}></script>
<script>

    {#车牌号ajax验证#}
    $("#user_number").blur(function () {
        var name = $("#user_number").val().replace(/(^\s*)|(\s*$)/g, "");

        if (name == "") {
            layer.msg("请输入正确的格式")
        } else {
            console.log(name)
            $.ajax({
                datapyte: "JSON",
                url: "{% url "My_Parking_Charge:VIPregister" %}",
                type: "POST",
                data: {'user_ID': name},
                success: function (e) {
                    if (e == "1") {
                        $("#user_span").addClass('layui-icon-ok')
                    } else {
                        layer.msg("该车牌号已注册", {icon: 5})

                    }


                }


            })
        }
    })


    {#手机号ajax验证#}
    $("#user_number3").blur(function () {
        var telephone = $("#user_number3").val().replace(/(^\s*)|(\s*$)/g, "");
        if (telephone == "") {
            layer.msg("请输入正确的格式")
        } else {
            $.ajax({
                url: "{% url "My_Parking_Charge:VIPregister" %}",
                datapyte: "json",
                type: "post",
                data: {'telephone': telephone},
                success: function (e) {
                    if (e == "1") {
                        $("#user_span2").addClass('layui-icon-ok')
                    } else {
                        layer.msg("该手机号已注册过", {icon: 5})
                    }

                }


            })
        }
    })
    {#其他input标签 失去焦点#}
    $("#user_number1").blur(function () {
        if ($("#user_number1").val() == "") {
            layer.msg("请输入正确的格式")
        } else {

            $("#user_span1").addClass('layui-icon-ok')
        }
    })
    $("#user_number4").blur(function () {
        if ($("#user_number1").val() == "") {
            layer.msg("请输入正确的格式")
        } else {
            $("#user_span3").addClass('layui-icon-ok')
        }
    })


    {#引用了layui的样式和方法，则下面的监听事件失效，被layui接管了#}
    {#    $('input[type=radio][name=sex]').change(function () {#}
    {#        console.log(this.value)#}
    {#        var s = $(this).val()#}
    {#        console.log(s)#}
    {##}
    {#        $("#user_span4").addClass('layui-icon-ok')#}
    {##}
    {#    })#}


    //Demo 表单提交
    layui.use('form', function () {

        var form = layui.form;
        //监听提交
        form.on('submit(formDemo)', function (data) {
            var dict = data.field
            {#console.log(data.form) //被执行提交的form对象，一般在存在form标签时才会返回#}
            console.log(data.field) //当前容器的全部表单字段，名值对形式：{name: value}
            console.log(dict.user_name,dict.sex)
            if (dict.user_number == '' || dict.user_name == '' || dict.user_phone == '' || dict.user_birth == '' || dict.sex == '') {
                layer.msg("不可为空！", {icon: 5})
            } else {
                $.ajax({
                    url: "{% url "My_Parking_Charge:myregister" %}",
                    type: "post",
                    datapyte: "json",
                    data: {
                        'user_name': dict.user_name, 'user_number': dict.user_number,
                        'user_birth': dict.user_birth, 'user_sex': dict.sex, 'user_phone': dict.user_phone
                    },
                    success: function (e) {
                        if (e == "1") {
                            layer.msg("注册成功！", {icon: 1})
                            setTimeout(function(){location.reload()}, 3000);//延时刷新
                        } else {
                            layer.msg("注册失败！", {icon: 2})
                        }

                    }


                })

                return false;
            }
        });
    });


    //日期选择器


    layui.use('laydate', function () {
        var laydate = layui.laydate;

        //执行一个laydate实例
        laydate.render({
            elem: '#user_number4' //指定元素
        });
    });

</script>
</body>
</html>